name: 'Hello World'
description: 'Greet someone and record the time'
branding:
  icon: 'heart'
  color: 'blue'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  flutter_version:
    description: 'Flutter version'
    default: '3.3.3'
  flutter_channel:
    description: 'Flutter channel'
    default: 'stable'


outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'node16'
  main: 'dist/index.js'

  


