name: 'Hello World'
description: 'Greet someone and record the time'
branding:
  icon: 'heart'
  color: 'blue'

inputs:

  flutter_version:
    description: 'Flutter version'
    required: false
    default: '3.3.3'


  flutter_channel:
    description: 'Flutter channel'
    required: false
    default: 'stable'


runs:
  using: "composite"
  steps:  
    # - uses: subosito/flutter-action@v1
    #   with:
    #     flutter-version: ${{inputs.flutter_version}}
    #     channel: ${{inputs.flutter_channel}}
    # - run: flutter pub get
    #   shell: bash
    # - run: flutter build apk 
    #   shell: bash

    - uses: ./src/
      id: hello
      with:
        path: '' 

      run: echo "The time was ${{ steps.hello.outputs.slack_result }}"
      shell: bash

